name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild MyApp.sln /restore /t:Build
      env:
        Configuration: ${{ matrix.configuration }}
